name: Publish

on:
  push:
    tags: ["*"]

env:
  CARGO_TERM_COLOR: always

jobs:
  publish-rust:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --verbose
      - name: Login
        run: cargo login ${{ secrets.CARGO_API_TOKEN }}
      - name: Publish
        run: cargo publish

  publish-wasm:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: wasm-pack-action
        uses: jetli/wasm-pack-action@v0.4.0
      - run: npm config set //registry.npmjs.org/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}
      - name: Builds
        run: wasm-pack build --features wasm
      - name: Publish
        run: wasm-pack publish
      - name: Set VERSION
        run: echo "VERSION=$(echo ${{github.ref_name}} | sed -e 's/[A-Za-z]*//')" >> $GITHUB_ENV
      - run: gh release create ${{ github.ref_name }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: gh release upload ${{ github.ref_name }} "./pkg/fi_verifiable_data.js" "./pkg/fi_verifiable_data_bg.wasm" "./pkg/fi_verifiable_data_bg.wasm.d.ts" "./pkg/fi_verifiable_data.d.ts"  "./dist/module/fidenz-maposm-${{ env.VERSION }}.tgz"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
